### ISSUE TITLE
发布组件失败

### ISSUE THREAD

**Issue by daief** [ymm-tech/gods-pen#19]
按照文档开发组件，基本上没有改动，执行发布时失败，提示 `403 - {"code":500,"msg":"请求不合法"}`。

![image](https://user-images.githubusercontent.com/19222089/66997079-63521e00-f104-11e9-881b-d7f15350fda4.png)

另外，在码良后台“左侧菜单-用户设置”查看的 token，每次切换一下页面就会变化，这是怎么回事？

顺便一提，形如 `xxxx.xx@huijie-inc.com` 的邮箱在此页面提示 `请输入正确的邮箱地址`。

**Comment by jy03078959** [comment]
检查 设置的host 是否是 https 协议。 检查授权 key是否正确。 这个问题只会是这两个原因之一。

**Comment by jy03078959** [comment]
> 不好意思，第一次还没编辑好，一个快捷键 cmd + enter 就发出去了。
> 
> `.godspen-config.json`。
> 
> ```json
> {
>   "token": "h7DGGSaD8AsWRhriS2XJ6WY684Rf4iRwmCnYrNyBw855BdaGTXxWwTDHGXTm6tHj",
>   "registry": "https://godspen.ymm56.com"
> }
> ```
> 
> `token` 是从管理后台里取的。

解决了吗

**Comment by daief** [comment]
没有解决，我只是贴一下我的配置而已，想看看是不是有错误。

**Comment by jy03078959** [comment]
你可以尝试 把后台的token信息 重置一下。在设置上去。 registry 没问题。 应该是 token 错误。

**Comment by daief** [comment]
解决了。

在这个页面要先点一次修改才行，居然没有默认设置 `token`，怪不得每次到这个页面 `token` 都不一样。

请把邮箱校验改一下吧，像我这种情况修改按钮就提交不了，我个人暂时通过其他方式提交了。

![image](https://user-images.githubusercontent.com/19222089/67069958-54757500-f1b1-11e9-97c5-2f32cc22b284.png)
