### ISSUE TITLE
编辑器中怎么看构建H5的源代码

### ISSUE THREAD

**Issue by zhangjun050754** [ymm-tech/gods-pen#21]
编辑器中怎么看构建H5的源代码

**Comment by jy03078959** [comment]
编辑器编辑的是一个json。然后有解析器解析。不存在导出编辑后的代码。可以参考  https://github.com/ymm-tech/gods-pen/wiki/%E7%A0%81%E8%89%AF%E7%B3%BB%E7%BB%9F%E6%A0%B8%E5%BF%83%E5%AE%9E%E7%8E%B0%E6%80%9D%E8%B7%AF  文章。会对你理解有帮助

**Comment by zhangjun050754** [comment]
> 编辑器编辑的是一个json。然后有解析器解析。不存在导出编辑后的代码。可以参考 https://github.com/ymm-tech/gods-pen/wiki/%E7%A0%81%E8%89%AF%E7%B3%BB%E7%BB%9F%E6%A0%B8%E5%BF%83%E5%AE%9E%E7%8E%B0%E6%80%9D%E8%B7%AF 文章。会对你理解有帮助

最终打包到服务端也是json？解析器是在服务端还是在编辑器里面？

**Comment by jy03078959** [comment]
> > 编辑器编辑的是一个json。然后有解析器解析。不存在导出编辑后的代码。可以参考 https://github.com/ymm-tech/gods-pen/wiki/%E7%A0%81%E8%89%AF%E7%B3%BB%E7%BB%9F%E6%A0%B8%E5%BF%83%E5%AE%9E%E7%8E%B0%E6%80%9D%E8%B7%AF 文章。会对你理解有帮助
> 
> 最终打包到服务端也是json？解析器是在服务端还是在编辑器里面 如果是编辑器里面的 解析后的代码应该是可以导出的。。

解析器的代码就在这个项目里面。叫做 client . 至于是否可以抽离处理，当然是可以抽离出来的。不过需要你比较熟悉这个系统。
