### ISSUE TITLE
如何做好设计稿适配，是否支持从 PSD 文件导入素材？

### ISSUE THREAD

**Issue by littlee** [ymm-tech/gods-pen#30]
- 设计师提供了 750*1334 的设计稿，但是编辑器只能做 320/360/414 的适配？只能通过一个个拉伸大小的方式？
- 从 PSD 导出切图后，需要
```
while (切图.length) {
  上传()
  看一眼设计稿()
  调整大小()
  看一眼设计稿()
  拖动到与设计稿对应的位置()
}
```
这个过程相当耗时，如果能直接导入 PSD 可以节省大量重复性操作

**Comment by jy03078959** [comment]
> * 设计师提供了 750*1334 的设计稿，但是编辑器只能做 320/360/414 的适配？只能通过一个个拉伸大小的方式？
> * 从 PSD 导出切图后，需要
> 
> ```
> while (切图.length) {
>   上传()
>   看一眼设计稿()
>   调整大小()
>   看一眼设计稿()
>   拖动到与设计稿对应的位置()
> }
> ```
> 
> 这个过程相当耗时，如果能直接导入 PSD 可以节省大量重复性操作

谢谢你的建议，我们考虑一下支持psd导入。
