### ISSUE TITLE
gods-pen和gods-pen-docker 关联不起来

### ISSUE THREAD

**Issue by fantasthu** [ymm-tech/gods-pen#32]
1.clone gods-pen
2.clone gods-pen-docker 
3.启动gods-pen,gods-pen-docker 
![image](https://user-images.githubusercontent.com/9922079/68190302-2208ac00-ffe8-11e9-8590-92e662177c1b.png)

![image](https://user-images.githubusercontent.com/9922079/68190278-10bf9f80-ffe8-11e9-90ef-5c9bd7465a77.png)
4.访问服务
![image](https://user-images.githubusercontent.com/9922079/68190403-482e4c00-ffe8-11e9-96d7-38ab54924c39.png)
5.你们项目非常好,但是文档不够细,完整的流程写细致点就完美了,如果可以很简单的部署就完美了

**Comment by jy03078959** [comment]
gods-pen和gods-pen-docker 是独立的。
gods-pen-docker 可以独立部署，部署后他里面会有整体运行环境，包括 gods-pen  gods-pen-admin  gods-pen-server mysql es ....   

gods-pen 只是一个编辑器，你如果想源代码部署，请产考文档   https://godspen.ymm56.com/doc/cookbook/source.html
