### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by zhangjanp** [ymm-tech/gods-pen#40]
Missing some file
[https://ymm-maliang.oss-cn-hangzhou.aliyuncs.com/truck/emptyContainer/1.0.2/editor.js](https://ymm-maliang.oss-cn-hangzhou.aliyuncs.com/truck/emptyContainer/1.0.2/editor.js)

**Comment by jy03078959** [comment]
这个不是问题。 这是在每个节点拖到编辑器里面的时候会尝试去加载对于的编辑器代码。有些组件没有对应编辑器。就会404. 不是问题。
