### ISSUE TITLE
后台版本能否提供基于Spring Boot + Mysql的

### ISSUE THREAD

**Issue by we-fight** [ymm-tech/gods-pen#42]

**Comment by jy03078959** [comment]
你可以只用码良的编辑器，然后页面的管理自己用 java+mysql 去做。这原理上是没问题的。因为码良编辑器只编辑配置json，最终提交给服务端保存，以及预览器获取服务端保存的数据，然后进行页面渲染显示。至于服务的实现都可以自己定制
