### ISSUE TITLE
关于如何实现不同设备的样式响应

### ISSUE THREAD

**Issue by welllin** [ymm-tech/gods-pen#47]
首先 很好的项目，获益匪浅，非常感谢。

这里有个疑问，码良如何实现在不同设备里面的响应？

我们这里普遍遇到的情况就是，在拖动了些组件后，样式被设置的非常固定。然后得自己手动的更改成百分比，为了达成不同设备的展示。

谢啦

**Comment by jy03078959** [comment]
以下回答只针对移动端：
1：在码良里面做的内容都是相对于宽 320px 做的。然后在不同分辨率的设备上显示，会按照等比放大做适配
2：码良平台也是在拖动后会被换算成固定大小。但是码良里面提供一种布局设置如下。你可以控制组件的对齐方式及位置达到在不同屏幕适配
![image](https://user-images.githubusercontent.com/3038488/75862962-b2da8180-5e3a-11ea-878b-463b13fdf4d4.png)

**Comment by welllin** [comment]
嗯嗯好的看到了，这里码良的适配针对不同设备做的的确不错的。我们遇到的问题是跟运行的环境对Viewport支持的不是很好，特别是针对安卓，苹果的一点问题都没有。

感谢了🙏
