### ISSUE TITLE
复杂组件之间的Animation是如何实现的？

### ISSUE THREAD

**Issue by welllin** [ymm-tech/gods-pen#48]
非常感谢这个工具，大大的提高我们的效率。

这里我们有点疑问关于如何实现几个组件之间的animation的交互呢？

链接里面解释了一些比较简单的animation，不过如果是2-3个以上的组件之间的动画该如何实现呢？

非常感谢

**Comment by jy03078959** [comment]
这个项目的初衷是做营销活动，所以我们尽量提供简单易用的动画可以快速添加到元素上。链接里面可以看到有一个动画控制面板，可以为每个元素添加多个阶段的动画

![image](https://user-images.githubusercontent.com/3038488/75941944-034def80-5ecc-11ea-90b2-43f4ba70214f.png)

**Comment by welllin** [comment]
感谢回复。

所以目前编辑器没有提供针对多个组件之间的复杂Animation的东西吗？比如按钮A的点击会trigger按钮B的旋转？目前我们似乎可以通过写入脚本里面，不过这样的话有点感觉hacking？

**Comment by jy03078959** [comment]
是的，目前还没有这种触发一个元素播放动画的功能。不过你的确可以通过写脚本支持，并且你这个脚本是可以复用的。比如你上面的场景就是把这个脚本添加到按钮上。脚本暴露一个方法，参数就是目标元素 以及要执行的动画。  

另外 感觉你已经在公司使用。希望你能填一下这个小小的问卷，我收集下q2的计划    https://ding.fanqier.cn/f/jhhnib6x?e_field=github  谢谢
