### ISSUE TITLE
很感谢YMM团队的付出，对这个项目很感兴趣，。。。

### ISSUE THREAD

**Issue by soulsoul** [ymm-tech/gods-pen#81]
项目开源的割接不够清晰，代码有很多内部的东西，配置项不清晰，资源的引用，也比较混乱。应该很多是内部使用的环境。
另外希望活跃社区， 加大开源力度，让门槛更低一些……

**Comment by jy03078959** [comment]
感谢提供的建议。我们在有限的精力里面做有限的事。因为业务太多的原因，目前对开源的内容支持力度会少很多。但是已有的内容能为社区提供一种参考。也希望有志者一起来推动。
